[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."saju"]
  timeout = 26

[[redirects]]
  from = "/api/saju"
  to = "/.netlify/functions/saju"
  status = 200
